In [2]:
import numpy as np


Create a NumPy array from a Python list.

In [3]:
ll = [1,0,2,0,25,36,5]
print(type(ll))
ll = np.array(ll)
print(ll)
print(type(ll))

<class 'list'>
[ 1  0  2  0 25 36  5]
<class 'numpy.ndarray'>


In [4]:
ll = np.array([])

In [5]:

np.append(ll, 10)

array([10.])

Create an array containing numbers 1–100.

In [6]:
ll = np.array([x for x in range(1,101)])
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [7]:
ll = np.arange(1,101)
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Create a 5×5 array of zeros.

In [8]:
ll = np.zeros((5,5))
print(ll)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
ll = np.zeros((5,5), dtype=int)

In [10]:
ll

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Create a 3×4 array of ones.

In [11]:
ll = np.ones((3,4))
ll

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
ll = np.ones((3,4), int)
ll

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Create a 5×5 identity matrix.

In [13]:
ll = np.identity(5, dtype=int)
ll

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create an array of even numbers from 2–100.

In [14]:
ll = np.array([x for x in range(2,100) if x %2 == 0])

ll

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [15]:
ll = np.arange(2,101,2)
ll

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create an array of odd numbers from 1–99.

In [16]:
ll = np.arange(1,99, 2)
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [17]:
ll = np.array([x for x in range(1,101) if x%2 == 1])
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Create a 3×3 matrix containing 1–9.

In [18]:
ll = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(ll)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
ll = np.arange(1,10).reshape(3,3)
ll

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Reshape a 1D array into a 2D matrix.

In [20]:
ll = np.arange(1,21)

In [21]:
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
ll = ll.reshape(4,5)

ll

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Flatten a 2D array.

In [23]:
ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Convert a 2D array into 1D.

In [24]:
ll = ll.reshape(4,5)

ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Find the shape of an array.

In [25]:
ll = ll.reshape(4,5)

In [26]:
ll.shape

(4, 5)

Find the number of dimensions.

In [27]:
ll.ndim

2

Find the total number of elements.

In [28]:
ll.size

20

Find the data type.

In [29]:
ll.dtype

dtype('int64')

Change the data type.

In [30]:
ll = ll.astype(float)

ll.dtype

dtype('float64')

In [31]:
import random


Generate 10 random integers.

In [32]:
ll = np.random.randint(1,1000,10)

ll


array([932, 613, 171, 580, 273, 793, 737, 346, 349, 476], dtype=int32)

Generate a random 5×5 matrix.

In [33]:
ll = np.random.randint(1,1000,25).reshape(5,5)
ll

array([[170, 273, 175, 567, 468],
       [515, 403, 485, 556, 911],
       [753, 600, 564, 631, 652],
       [674,   1, 874, 374, 255],
       [365, 582, 830,  54, 659]], dtype=int32)

In [34]:
ll = np.random.random(25).reshape(5,5)
ll

array([[0.88560311, 0.82070279, 0.84313245, 0.28221431, 0.73113533],
       [0.26840302, 0.87953551, 0.43113338, 0.54081161, 0.57656715],
       [0.58765505, 0.36691551, 0.60657974, 0.01998364, 0.31253089],
       [0.985522  , 0.65292182, 0.22129087, 0.82826186, 0.47157479],
       [0.9082639 , 0.36949806, 0.07567443, 0.61824549, 0.96561912]])

Generate 20 random numbers between 0 and 1.

In [35]:
ll = np.random.random(20)

In [36]:
ll

array([0.34001189, 0.13830843, 0.49185721, 0.77280576, 0.68444133,
       0.47421465, 0.98369057, 0.72105282, 0.85193566, 0.85928702,
       0.93367375, 0.80338202, 0.45137507, 0.95713534, 0.89654791,
       0.95090599, 0.15703952, 0.31183912, 0.82524921, 0.1713448 ])

Generate 10 random integers between 1 and 100.

In [37]:
ll = np.random.randint(1,100, 10)
ll

array([32, 68, 68, 42, 96, 55, 16, 90, 34, 19], dtype=int32)

Add two NumPy arrays.

In [38]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 + arr2
final

array([ 8, 10, 12, 19,  7, 42])

Subtract two NumPy arrays.

In [39]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 - arr2
final

array([ -6,  -6,  -6, -11,   3, -30])

Multiply two arrays element-wise.

In [40]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 * arr2
final

array([  7,  16,  27,  60,  10, 216])

Divide two arrays element-wise.

In [41]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 / arr2
final

array([0.14285714, 0.25      , 0.33333333, 0.26666667, 2.5       ,
       0.16666667])

Calculate the square of every element.

In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.square(arr)
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

Calculate the cube of every element.

In [43]:
arr = np.array([1,2,3,4,5,6,7,8,9])
final = arr * arr * arr
final

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [44]:
arr = np.array([1,2,3,4,5,6,7,8,9])
final = arr **3
final

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [45]:
arr = np.array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

arr = np.sqrt(arr)
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Calculate absolute values.

In [46]:
arr = np.array([-5, -2, 0, 3, 7])
arr = np.abs(arr)
arr

array([5, 2, 0, 3, 7])

In [47]:
arr = np.array([5, 2, 0, 3, 7])
arr = np.exp(arr)
arr

array([1.48413159e+02, 7.38905610e+00, 1.00000000e+00, 2.00855369e+01,
       1.09663316e+03])

Calculate logarithm of every element.

In [48]:
arr = np.array([5, 2,5, 3, 7])
arr = np.log(arr)
arr

array([1.60943791, 0.69314718, 1.60943791, 1.09861229, 1.94591015])

Find maximum value.

In [49]:
arr = np.array([5, 2,5, 3, 7])
max(arr)

np.int64(7)

Find minimum value.

In [50]:
arr = np.array([5, 2,5, 3, 7])
min(arr)

np.int64(2)

Calculate sum.

In [51]:
arr = np.array([5, 2,5, 3, 7])
sum(arr)

np.int64(22)

Calculate mean.

In [52]:
arr = np.array([5, 2,5, 3, 7])
mean = np.mean(arr)
print(mean)

4.4


Calculate median.

In [53]:
arr = np.array([5, 2,5, 3, 7])
median = np.median(arr)
print(median)

5.0


Calculate standard deviation.

In [54]:
arr = np.array([5, 2,5, 3, 7])
std = np.std(arr)
print(std)

1.7435595774162693


Calculate variance.


In [55]:
arr = np.array([5, 2,5, 3, 7])
var = np.var(arr)
print(var)

3.04


Calculate cumulative sum.

Calculate cumulative sum.

In [56]:
arr = np.array([5, 2,5, 3, 7])
cumulative_sum = np.cumulative_sum(arr)
print(cumulative_sum)

[ 5  7 12 15 22]


Calculate percentiles.

In [57]:
arr = np.array([5, 2,5, 3, 7])
percentile = np.percentile(arr, 100)
print(percentile)

7.0


Extract the first five elements.

In [58]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
first_five = arr[:5]
print(first_five)

[5 2 5 3 7]


In [59]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
first_five = np.take(arr,range(5))
print(first_five)

[5 2 5 3 7]


Extract every second element.

In [60]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
every_second_el = arr[::2]
print(every_second_el)

[5 5 7 5 6]


Reverse an array.

In [61]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
reverse_arr = arr[::-1]
print(reverse_arr)

[8 6 2 5 4 7 3 5 2 5]


Extract a specific row.

In [62]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


row = arr[1]
row

array([4, 5, 6])

Extract a specific column.

In [63]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

column = arr[:, 1]
column

array([2, 5, 8])

Extract a submatrix.

In [64]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

sub = arr[1:3, 1:3]
sub

array([[ 6,  7],
       [10, 11]])

In [67]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, -7, 8],
    [9, -10, 11, 12],
    [13, 14, 15, -16]
])
arr[arr < 0] = 0
print(arr)

[[ 1  0  3  4]
 [ 5  6  0  8]
 [ 9  0 11 12]
 [13 14 15  0]]


In [69]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, -7, 8],
    [9, -10, 11, 12],
    [13, 14, 15, -16]
])
arr = np.where(arr < 0, 0, arr)
arr

array([[ 1,  0,  3,  4],
       [ 5,  6,  0,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15,  0]])

Cap values greater than 50 at 50.

In [74]:
arr = np.random.randint(1,100,10)
print(arr)
arr[arr > 50] = 50
print(arr)


[ 6 33 66 41 90 31 57 79 87 42]
[ 6 33 50 41 50 31 50 50 50 42]


In [75]:
arr = np.random.randint(1,100,10)
print(arr)
arr = np.where(arr > 50, 50, arr)
print(arr)


[91 54 88 41 49 61 87 40  3 24]
[50 50 50 41 49 50 50 40  3 24]


Find values greater than the mean.

In [78]:
arr = np.random.randint(1,100,10)
print(arr)
mean = np.mean(arr)
print(mean)
arr = arr[np.where(arr > mean)]
print(arr)

[ 1 76 37 31 57 17 98 54 46 75]
49.2
[76 57 98 54 75]


Find all even numbers.

In [80]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where(arr % 2 == 0)]
print(arr)

[29 79  7 38 83 74 79 96 95 82 18 85 57 37 41 76 58 86 86  2  7 66 60 13
 12]
[38 74 96 82 18 76 58 86 86  2 66 60 12]


Find all odd numbers.

In [81]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where(arr % 2 == 1)]
print(arr)

[45 15 46 99 54 57  8 50 59 31 18 43 47 41 46 49 29 79  3 55 55 20  2 24
 58]
[45 15 99 57 59 31 43 47 41 49 29 79  3 55 55]


Find values between 20 and 50.

In [91]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where((arr > 20) & (arr < 50))]
print(arr)

[64 19 70 76 11 47  6 35  9 70 69 97 48  9 39 43 88 96 21 14  9 88 31 19
 57]
[47 35 48 39 43 21 31]


Count values above a threshold.

In [92]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[arr > 50]
print(arr)
print(len(arr))

[ 9 65 67 30 52  4 26 59 14  5 13 51 30 28 19 80 44 80 83 87 93 66 30 31
  5]
[65 67 52 59 51 80 80 83 87 93 66]
11


Find indices where values exceed 100.

In [94]:
arr = np.random.randint(1,200,25)
print(arr)
arr = np.where(arr > 100)
print(arr)
print(len(arr))

[ 55  32 151 134  31 153  75 119 149 191  99   6 119 121  87 190  23  29
  19 116 133 151  73  14 115]
(array([ 2,  3,  5,  7,  8,  9, 12, 13, 15, 19, 20, 21, 24]),)
1


Replace NaN values with zero.

In [102]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr = np.nan_to_num(arr, 0)

print(arr)

[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
[[  1.  -2.   3.   4.]
 [  5.   6.   0.   8.]
 [  9. -10.   0.  12.]
 [ 13.  14.  15. -16.]]


In [110]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr[np.isnan(arr)] = 0
print(arr)


[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
[[  1.  -2.   3.   4.]
 [  5.   6.   0.   8.]
 [  9. -10.   0.  12.]
 [ 13.  14.  15. -16.]]


Find NaN values.

In [112]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr = np.where(np.isnan(arr))
print(arr)

[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
(array([1, 2]), array([2, 2]))


Count NaN values.

In [121]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
print(arr)
arr = np.where(np.isnan(arr))
print(len(arr[0]))

[ 1.  2.  5.  3.  6. nan 12. nan 15. nan]
3


In [122]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
print(arr)
print(np.sum(np.isnan(arr)))

[ 1.  2.  5.  3.  6. nan 12. nan 15. nan]
3


Remove NaN values from an array.

In [126]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
arr = arr[~np.isnan(arr)]
print(arr)

[ 1.  2.  5.  3.  6. 12. 15.]


Find unique elements.

In [130]:
arr = np.array([1,1,2,2,3,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
unique = np.unique(arr)
print(unique)

[ 1.  2.  3.  5.  6. 12. 15. nan]


Add two matrices.

In [134]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 + arr2)

[[  2  -4   6   8]
 [ 10  13   7  16]
 [ 18 -20   8  24]
 [ 26  28  30 -32]]


Multiply two matrices.

In [135]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 * arr2)

[[  1   4   9  16]
 [ 25  42  10  64]
 [ 81 100   7 144]
 [169 196 225 256]]


Perform matrix multiplication using @.

In [136]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 @ arr2)

[[  70   10   74  -40]
 [ 157  124  179  -36]
 [ 124   70  164 -224]
 [  10 -302  -26  600]]


Calculate matrix transpose.

In [138]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

arr = np.transpose(arr)
print(arr)

[[  1   5   9  13]
 [ -2   6 -10  14]
 [  3   2   1  15]
 [  4   8  12 -16]]


Calculate matrix inverse.

In [ ]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

arr = np.linalg.inv(arr)
print(arr)

[[ -2   1  -4  -5]
 [ -6  -7  -3  -9]
 [-10   9  -2 -13]
 [-14 -15 -16  15]]


Calculate determinant.

In [141]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.linalg.det(arr))

14304.000000000011


Calculate eigenvalues.

In [142]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.linalg.eigvals(arr))

[-27.10196718+0.j         -3.64777322+0.j         11.3748702 +3.9114076j
  11.3748702 -3.9114076j]


Calculate eigenvectors.

In [146]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

eigenvalues, eigenvectors = np.linalg.eig(arr)

print( eigenvectors)

[[ 0.09510768+0.j         -0.64990105+0.j          0.08565795+0.14587258j
   0.08565795-0.14587258j]
 [ 0.1756453 +0.j          0.00929265+0.j          0.76994598+0.j
   0.76994598-0.j        ]
 [ 0.41172465+0.j          0.72962604+0.j          0.00149001+0.35367369j
   0.00149001-0.35367369j]
 [-0.88914907+0.j          0.21257497+0.j          0.46338624+0.19685779j
   0.46338624-0.19685779j]]


Solve a system of linear equations.

In [148]:
'''2x + y = 5
    x - y = 1
    
    linear equestions

    AX = B

    
    
    '''

A = [[2,  1],
     [1, -1]]

X = ['x', 'y']

B = [5, 1]

np.linalg.solve(A, B)

array([2., 1.])

Calculate dot product.

In [149]:
A = np.array([1,2,3])
B = np.array([1,2,3])

dot = np.dot(A, B)
dot

np.int64(14)

Calculate cross product.

In [152]:
A = np.array([1,2,3])
B = np.array([2,2,1])

cross = np.cross(A, B)
cross

array([-4,  5, -2])

Calculate vector magnitude.

In [153]:
vec = np.array([2,5,6])

print(np.linalg.norm(vec))

8.06225774829855


Normalize a vector.

In [154]:
vec = np.array([2,5,6])

magnitude = np.linalg.norm(vec)
print(magnitude)
vec = vec / magnitude

print(vec)
print(np.linalg.norm(vec))

8.06225774829855
[0.24806947 0.62017367 0.74420841]
1.0


Calculate Euclidean distance.

In [157]:
vec1 = np.array([2,3,5])
vec2 = np.array([2,5,5])

print(np.linalg.norm(vec1 - vec2))

2.0


Calculate cosine similarity.

In [170]:
vec1 = np.array([2,3,5])
vec2 = np.array([-2,-3,-5])

cosine_similarity = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
print(cosine_similarity)

-1.0000000000000002


Calculate row-wise sums.

In [173]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.sum(arr, 1))

[ 6 21 12 26]


Calculate column-wise sums.

In [174]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.sum(arr, 0))

[28  8 21  8]


Calculate row-wise means.

In [175]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.mean(arr, 1))

[1.5  5.25 3.   6.5 ]


Calculate column-wise means.

In [176]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.mean(arr, 0))

[7.   2.   5.25 2.  ]
