In [1]:
import numpy as np


Create a NumPy array from a Python list.

In [2]:
ll = [1,0,2,0,25,36,5]
print(type(ll))
ll = np.array(ll)
print(ll)
print(type(ll))

<class 'list'>
[ 1  0  2  0 25 36  5]
<class 'numpy.ndarray'>


In [3]:
ll = np.array([])

In [4]:

np.append(ll, 10)

array([10.])

Create an array containing numbers 1–100.

In [5]:
ll = np.array([x for x in range(1,101)])
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [6]:
ll = np.arange(1,101)
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Create a 5×5 array of zeros.

In [7]:
ll = np.zeros((5,5))
print(ll)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
ll = np.zeros((5,5), dtype=int)

In [9]:
ll

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Create a 3×4 array of ones.

In [10]:
ll = np.ones((3,4))
ll

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
ll = np.ones((3,4), int)
ll

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Create a 5×5 identity matrix.

In [12]:
ll = np.identity(5, dtype=int)
ll

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create an array of even numbers from 2–100.

In [13]:
ll = np.array([x for x in range(2,100) if x %2 == 0])

ll

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
ll = np.arange(2,101,2)
ll

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create an array of odd numbers from 1–99.

In [15]:
ll = np.arange(1,99, 2)
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [16]:
ll = np.array([x for x in range(1,101) if x%2 == 1])
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Create a 3×3 matrix containing 1–9.

In [17]:
ll = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(ll)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
ll = np.arange(1,10).reshape(3,3)
ll

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Reshape a 1D array into a 2D matrix.

In [19]:
ll = np.arange(1,21)

In [20]:
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
ll = ll.reshape(4,5)

ll

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Flatten a 2D array.

In [22]:
ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Convert a 2D array into 1D.

In [23]:
ll = ll.reshape(4,5)

ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Find the shape of an array.

In [24]:
ll = ll.reshape(4,5)

In [25]:
ll.shape

(4, 5)

Find the number of dimensions.

In [26]:
ll.ndim

2

Find the total number of elements.

In [27]:
ll.size

20

Find the data type.

In [28]:
ll.dtype

dtype('int64')

Change the data type.

In [29]:
ll = ll.astype(float)

ll.dtype

dtype('float64')

In [30]:
import random


Generate 10 random integers.

In [31]:
ll = np.random.randint(1,1000,10)

ll


array([591, 405, 987,  72,  86, 678, 503, 101, 989, 937], dtype=int32)

Generate a random 5×5 matrix.

In [32]:
ll = np.random.randint(1,1000,25).reshape(5,5)
ll

array([[746, 741, 100, 564, 665],
       [271, 151, 279, 280, 959],
       [227, 735, 390,  57, 754],
       [542, 623, 121, 689, 725],
       [273,  74, 122, 288, 149]], dtype=int32)

In [33]:
ll = np.random.random(25).reshape(5,5)
ll

array([[0.90073418, 0.2090078 , 0.68171537, 0.45328654, 0.83374528],
       [0.74102156, 0.60745239, 0.99702016, 0.53990613, 0.62965735],
       [0.34100439, 0.78106452, 0.04978878, 0.28063384, 0.44301733],
       [0.31470387, 0.56848525, 0.48080491, 0.53645744, 0.07828518],
       [0.04293906, 0.0746124 , 0.88400913, 0.2616452 , 0.63109498]])

Generate 20 random numbers between 0 and 1.

In [34]:
ll = np.random.random(20)

In [35]:
ll

array([0.41615796, 0.14891893, 0.27280825, 0.21863735, 0.85359888,
       0.42514228, 0.79142098, 0.91733618, 0.88758566, 0.27624816,
       0.05809706, 0.93655131, 0.58974406, 0.183782  , 0.24243972,
       0.47377488, 0.45281648, 0.11722561, 0.46225267, 0.05112737])

Generate 10 random integers between 1 and 100.

In [36]:
ll = np.random.randint(1,100, 10)
ll

array([62, 67, 65, 79, 75, 89, 54, 36, 43, 16], dtype=int32)

Add two NumPy arrays.

In [37]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 + arr2
final

array([ 8, 10, 12, 19,  7, 42])

Subtract two NumPy arrays.

In [38]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 - arr2
final

array([ -6,  -6,  -6, -11,   3, -30])

Multiply two arrays element-wise.

In [39]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 * arr2
final

array([  7,  16,  27,  60,  10, 216])

Divide two arrays element-wise.

In [40]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,15,2,36])

final = arr1 / arr2
final

array([0.14285714, 0.25      , 0.33333333, 0.26666667, 2.5       ,
       0.16666667])

Calculate the square of every element.

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr = np.square(arr)
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

Calculate the cube of every element.

In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9])
final = arr * arr * arr
final

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [43]:
arr = np.array([1,2,3,4,5,6,7,8,9])
final = arr **3
final

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [44]:
arr = np.array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

arr = np.sqrt(arr)
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

Calculate absolute values.

In [45]:
arr = np.array([-5, -2, 0, 3, 7])
arr = np.abs(arr)
arr

array([5, 2, 0, 3, 7])

In [46]:
arr = np.array([5, 2, 0, 3, 7])
arr = np.exp(arr)
arr

array([1.48413159e+02, 7.38905610e+00, 1.00000000e+00, 2.00855369e+01,
       1.09663316e+03])

Calculate logarithm of every element.

In [47]:
arr = np.array([5, 2,5, 3, 7])
arr = np.log(arr)
arr

array([1.60943791, 0.69314718, 1.60943791, 1.09861229, 1.94591015])

Find maximum value.

In [48]:
arr = np.array([5, 2,5, 3, 7])
max(arr)

np.int64(7)

Find minimum value.

In [49]:
arr = np.array([5, 2,5, 3, 7])
min(arr)

np.int64(2)

Calculate sum.

In [50]:
arr = np.array([5, 2,5, 3, 7])
sum(arr)

np.int64(22)

Calculate mean.

In [51]:
arr = np.array([5, 2,5, 3, 7])
mean = np.mean(arr)
print(mean)

4.4


Calculate median.

In [52]:
arr = np.array([5, 2,5, 3, 7])
median = np.median(arr)
print(median)

5.0


Calculate standard deviation.

In [53]:
arr = np.array([5, 2,5, 3, 7])
std = np.std(arr)
print(std)

1.7435595774162693


Calculate variance.


In [54]:
arr = np.array([5, 2,5, 3, 7])
var = np.var(arr)
print(var)

3.04


Calculate cumulative sum.

Calculate cumulative sum.

In [55]:
arr = np.array([5, 2,5, 3, 7])
cumulative_sum = np.cumulative_sum(arr)
print(cumulative_sum)

[ 5  7 12 15 22]


Calculate percentiles.

In [56]:
arr = np.array([5, 2,5, 3, 7])
percentile = np.percentile(arr, 100)
print(percentile)

7.0


Extract the first five elements.

In [57]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
first_five = arr[:5]
print(first_five)

[5 2 5 3 7]


In [58]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
first_five = np.take(arr,range(5))
print(first_five)

[5 2 5 3 7]


Extract every second element.

In [59]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
every_second_el = arr[::2]
print(every_second_el)

[5 5 7 5 6]


Reverse an array.

In [60]:
arr = np.array([5, 2,5, 3, 7,4,5,2,6,8])
reverse_arr = arr[::-1]
print(reverse_arr)

[8 6 2 5 4 7 3 5 2 5]


Extract a specific row.

In [61]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])


row = arr[1]
row

array([4, 5, 6])

Extract a specific column.

In [62]:
arr = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

column = arr[:, 1]
column

array([2, 5, 8])

Extract a submatrix.

In [63]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

sub = arr[1:3, 1:3]
sub

array([[ 6,  7],
       [10, 11]])

In [64]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, -7, 8],
    [9, -10, 11, 12],
    [13, 14, 15, -16]
])
arr[arr < 0] = 0
print(arr)

[[ 1  0  3  4]
 [ 5  6  0  8]
 [ 9  0 11 12]
 [13 14 15  0]]


In [65]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, -7, 8],
    [9, -10, 11, 12],
    [13, 14, 15, -16]
])
arr = np.where(arr < 0, 0, arr)
arr

array([[ 1,  0,  3,  4],
       [ 5,  6,  0,  8],
       [ 9,  0, 11, 12],
       [13, 14, 15,  0]])

Cap values greater than 50 at 50.

In [66]:
arr = np.random.randint(1,100,10)
print(arr)
arr[arr > 50] = 50
print(arr)


[ 7 67 22 13 90 21 66 65 67  3]
[ 7 50 22 13 50 21 50 50 50  3]


In [67]:
arr = np.random.randint(1,100,10)
print(arr)
arr = np.where(arr > 50, 50, arr)
print(arr)


[72 77 96 78 18  1 69 36 91 53]
[50 50 50 50 18  1 50 36 50 50]


Find values greater than the mean.

In [68]:
arr = np.random.randint(1,100,10)
print(arr)
mean = np.mean(arr)
print(mean)
arr = arr[np.where(arr > mean)]
print(arr)

[11 59 56 17 29  6 61 56 87 52]
43.4
[59 56 61 56 87 52]


Find all even numbers.

In [69]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where(arr % 2 == 0)]
print(arr)

[90 27  2 75 74  3 59 83 43 93 50 80 96 76 57 55 90 40 16 27 48 11 57 92
 17]
[90  2 74 50 80 96 76 90 40 16 48 92]


Find all odd numbers.

In [70]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where(arr % 2 == 1)]
print(arr)

[ 3 23  2 92 39  2 57 61 70 16 90 13 82 75 70 12 57  1 89 91  3 31 10 43
 17]
[ 3 23 39 57 61 13 75 57  1 89 91  3 31 43 17]


Find values between 20 and 50.

In [71]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[np.where((arr > 20) & (arr < 50))]
print(arr)

[70 25 31  5 96 29 51 45 44 37 54 28 76 92 51  6 20 74 62 19 56 37 87 87
 44]
[25 31 29 45 44 37 28 37 44]


Count values above a threshold.

In [72]:
arr = np.random.randint(1,100,25)
print(arr)
arr = arr[arr > 50]
print(arr)
print(len(arr))

[62 97 20  5 97 64 14 49 76 77 27  5 13 82 21 22 53 28 83 27 62 77 29 24
 82]
[62 97 97 64 76 77 82 53 83 62 77 82]
12


Find indices where values exceed 100.

In [73]:
arr = np.random.randint(1,200,25)
print(arr)
arr = np.where(arr > 100)
print(arr)
print(len(arr))

[173   7 160  67  69   5   3  81  10   3  69  56 165 124  41  91 133 102
  94  53  25 186 162 121  38]
(array([ 0,  2, 12, 13, 16, 17, 21, 22, 23]),)
1


Replace NaN values with zero.

In [74]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr = np.nan_to_num(arr, 0)

print(arr)

[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
[[  1.  -2.   3.   4.]
 [  5.   6.   0.   8.]
 [  9. -10.   0.  12.]
 [ 13.  14.  15. -16.]]


In [75]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr[np.isnan(arr)] = 0
print(arr)


[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
[[  1.  -2.   3.   4.]
 [  5.   6.   0.   8.]
 [  9. -10.   0.  12.]
 [ 13.  14.  15. -16.]]


Find NaN values.

In [76]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, np.nan, 8],
    [9, -10, np.nan, 12],
    [13, 14, 15, -16]
])
print(arr)
arr = np.where(np.isnan(arr))
print(arr)

[[  1.  -2.   3.   4.]
 [  5.   6.  nan   8.]
 [  9. -10.  nan  12.]
 [ 13.  14.  15. -16.]]
(array([1, 2]), array([2, 2]))


Count NaN values.

In [77]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
print(arr)
arr = np.where(np.isnan(arr))
print(len(arr[0]))

[ 1.  2.  5.  3.  6. nan 12. nan 15. nan]
3


In [78]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
print(arr)
print(np.sum(np.isnan(arr)))

[ 1.  2.  5.  3.  6. nan 12. nan 15. nan]
3


Remove NaN values from an array.

In [79]:
arr = np.array([1,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
arr = arr[~np.isnan(arr)]
print(arr)

[ 1.  2.  5.  3.  6. 12. 15.]


Find unique elements.

In [80]:
arr = np.array([1,1,2,2,3,2,5,3,6,np.nan, 12, np.nan, 15, np.nan])
unique = np.unique(arr)
print(unique)

[ 1.  2.  3.  5.  6. 12. 15. nan]


Add two matrices.

In [81]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 + arr2)

[[  2  -4   6   8]
 [ 10  13   7  16]
 [ 18 -20   8  24]
 [ 26  28  30 -32]]


Multiply two matrices.

In [82]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 * arr2)

[[  1   4   9  16]
 [ 25  42  10  64]
 [ 81 100   7 144]
 [169 196 225 256]]


Perform matrix multiplication using @.

In [83]:
arr1 = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])
arr2 = np.array([
    [1, -2, 3, 4],
    [5, 7, 5, 8],
    [9, -10, 7, 12],
    [13, 14, 15, -16]
])
print(arr1 @ arr2)

[[  70   10   74  -40]
 [ 157  124  179  -36]
 [ 124   70  164 -224]
 [  10 -302  -26  600]]


Calculate matrix transpose.

In [84]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

arr = np.transpose(arr)
print(arr)

[[  1   5   9  13]
 [ -2   6 -10  14]
 [  3   2   1  15]
 [  4   8  12 -16]]


Calculate matrix inverse.

In [85]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

arr = np.linalg.inv(arr)
print(arr)

[[-1.72818792e-01  1.67785235e-02  8.22147651e-02  2.68456376e-02]
 [-4.16666667e-02  8.33333333e-02 -4.16666667e-02 -1.40946282e-18]
 [ 2.66219239e-01 -2.90827740e-02 -4.25055928e-02  2.01342282e-02]
 [ 7.27069351e-02  5.92841163e-02 -9.50782998e-03 -2.18120805e-02]]


Calculate determinant.

In [86]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.linalg.det(arr))

14304.000000000011


Calculate eigenvalues.

In [87]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.linalg.eigvals(arr))

[-27.10196718+0.j         -3.64777322+0.j         11.3748702 +3.9114076j
  11.3748702 -3.9114076j]


Calculate eigenvectors.

In [88]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

eigenvalues, eigenvectors = np.linalg.eig(arr)

print( eigenvectors)

[[ 0.09510768+0.j         -0.64990105+0.j          0.08565795+0.14587258j
   0.08565795-0.14587258j]
 [ 0.1756453 +0.j          0.00929265+0.j          0.76994598+0.j
   0.76994598-0.j        ]
 [ 0.41172465+0.j          0.72962604+0.j          0.00149001+0.35367369j
   0.00149001-0.35367369j]
 [-0.88914907+0.j          0.21257497+0.j          0.46338624+0.19685779j
   0.46338624-0.19685779j]]


Solve a system of linear equations.

In [89]:
'''2x + y = 5
    x - y = 1
    
    linear equestions

    AX = B

    
    
    '''

A = [[2,  1],
     [1, -1]]

X = ['x', 'y']

B = [5, 1]

np.linalg.solve(A, B)

array([2., 1.])

Calculate dot product.

In [90]:
A = np.array([1,2,3])
B = np.array([1,2,3])

dot = np.dot(A, B)
dot

np.int64(14)

Calculate cross product.

In [91]:
A = np.array([1,2,3])
B = np.array([2,2,1])

cross = np.cross(A, B)
cross

array([-4,  5, -2])

Calculate vector magnitude.

In [92]:
vec = np.array([2,5,6])

print(np.linalg.norm(vec))

8.06225774829855


Normalize a vector.

In [93]:
vec = np.array([2,5,6])

magnitude = np.linalg.norm(vec)
print(magnitude)
vec = vec / magnitude

print(vec)
print(np.linalg.norm(vec))

8.06225774829855
[0.24806947 0.62017367 0.74420841]
1.0


Calculate Euclidean distance.

In [94]:
vec1 = np.array([2,3,5])
vec2 = np.array([2,5,5])

print(np.linalg.norm(vec1 - vec2))

2.0


Calculate cosine similarity.

In [95]:
vec1 = np.array([2,3,5])
vec2 = np.array([-2,-3,-5])

cosine_similarity = np.dot(vec1, vec2) / (np.linalg.norm(vec1) * np.linalg.norm(vec2))
print(cosine_similarity)

-1.0000000000000002


Calculate row-wise sums.

In [96]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.sum(arr, 1))

[ 6 21 12 26]


Calculate column-wise sums.

In [97]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.sum(arr, 0))

[28  8 21  8]


Calculate row-wise means.

In [98]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.mean(arr, 1))

[1.5  5.25 3.   6.5 ]


Calculate column-wise means.

In [99]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

print(np.mean(arr, 0))

[7.   2.   5.25 2.  ]


Find the row with maximum sum.

In [100]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

row_sum = np.sum(arr, 1)
print(row_sum)
max_idx = np.argmax(row_sum)
print(max_idx)


[ 6 21 12 26]
3


Perform broadcasting between arrays.

In [101]:
A = np.array([[1, 2, 3],
     [4, 5, 6]])

B = [10, 20, 30]


result = A+B
result

array([[11, 22, 33],
       [14, 25, 36]])

Normalize every column.


In [102]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

arr = np.linalg.norm(arr, 1)
arr

np.float64(40.0)

Normalize every column.

In [103]:
'''
for normlizeation we use min-max normlization
formula:   (x-min)/(max-min)
'''

arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])

column_min = np.min(arr, 0)
column_max = np.max(arr, 0)
print(column_min, column_max)


norm_arr = (arr-column_min)/ (column_max-column_min)
print(norm_arr)


[  1 -10   1 -16] [13 14 15 12]
[[0.         0.33333333 0.14285714 0.71428571]
 [0.33333333 0.66666667 0.07142857 0.85714286]
 [0.66666667 0.         0.         1.        ]
 [1.         1.         1.         0.        ]]


Standardize every column.

In [104]:
"""
For standardize every column
transform data through Z-score standardization

Formula:  Z = (x − mean) / standard deviation
"""

arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16]
])


column_mean = np.mean(arr, 0)
print(column_mean)
column_std = np.std(arr, 0)
print(column_std)

arr = (arr - column_mean)/ column_std
print(arr)

[7.   2.   5.25 2.  ]
[ 4.47213595  8.94427191  5.67340286 10.77032961]
[[-1.34164079 -0.4472136  -0.39658738  0.18569534]
 [-0.4472136   0.4472136  -0.57284844  0.55708601]
 [ 0.4472136  -1.34164079 -0.7491095   0.92847669]
 [ 1.34164079  1.34164079  1.71854533 -1.67125804]]


Find duplicate rows.

In [105]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])

unique_row, count = np.unique(arr, axis=0, return_counts=True)

duplicate_row = unique_row[count > 1]

print(duplicate_row)

[[ 13  14  15 -16]]


Remove duplicate rows.

In [106]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])

arr = np.unique(arr, axis=0)
print(arr)

[[  1  -2   3   4]
 [  5   6   2   8]
 [  9 -10   1  12]
 [ 13  14  15 -16]]


Sort a NumPy array.

In [107]:
arr = np.array([1,2,3,1,5,3,25,3,41])
arr = np.sort(arr)
print(arr)

[ 1  1  2  3  3  3  5 25 41]


Sort every row of a matrix.

In [108]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])
arr = np.sort(arr, axis=1)
print(arr)

[[ -2   1   3   4]
 [  2   5   6   8]
 [-10   1   9  12]
 [-16  13  14  15]
 [-16  13  14  15]]


Sort every column of a matrix.

In [109]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])

arr = np.sort(arr, axis=0)
print(arr)

[[  1 -10   1 -16]
 [  5  -2   2 -16]
 [  9   6   3   4]
 [ 13  14  15   8]
 [ 13  14  15  12]]


Find top 5 largest elements.

In [110]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])

arr = arr.flatten()
arr = np.sort(arr)
top_5_max = arr[-1:-6:-1]
top_5_max

array([15, 15, 14, 14, 13])

Find indices of top 5 values. 

In [111]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])

newarr = arr.flatten()
newarr = np.sort(arr)
top_5_max = newarr[:5]
top_5_max

array([[ -2,   1,   3,   4],
       [  2,   5,   6,   8],
       [-10,   1,   9,  12],
       [-16,  13,  14,  15],
       [-16,  13,  14,  15]])

In [112]:
arr = np.array([
    [1, -2, 3, 4],
    [5, 6, 2, 8],
    [9, -10, 1, 12],
    [13, 14, 15, -16],
    [13, 14, 15, -16]
])
new_arr = arr.flatten()
new_ind= np.argsort(new_arr)
print(new_ind)

top5_indices = new_ind[-5:][::-1]

print(np.unravel_index(top5_indices, arr.shape))

[15 19  9  1 10  0  6  2  3  4  5  7  8 11 16 12 17 13 14 18]
(array([4, 3, 3, 4, 3]), array([2, 2, 1, 1, 0]))


Split an array into equal parts.

In [113]:
arr = np.array([15, 19,  9,  1, 10,  0,  6,  2,  3,  4,  5,  7,  8, 11, 16, 12, 17, 13, 14, 18])
print(np.split(arr,2))

[array([15, 19,  9,  1, 10,  0,  6,  2,  3,  4]), array([ 5,  7,  8, 11, 16, 12, 17, 13, 14, 18])]


Concatenate two arrays.

In [114]:
arr1 = np.array([2,3,56,2,42,6,52,5,2562,])
arr2 = np.array([2,5,2,66,5,8,452,4,2,68,5])
print(np.concatenate((arr1, arr2)))

[   2    3   56    2   42    6   52    5 2562    2    5    2   66    5
    8  452    4    2   68    5]


Stack arrays vertically.

In [115]:
A = np.array([[1, 2, 3],
    [4,  5,  6]])

B = np.array([[7,  8,  9],
    [10, 11, 12]])

result = np.vstack((A,B))
result

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Stack arrays horizontally.

In [116]:
A = np.array([[1, 2, 3],
    [4,  5,  6]])

B = np.array([[7,  8,  9],
    [10, 11, 12]])

result = np.hstack((A,B))
result

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Create one-hot encoding using NumPy.

In [128]:

labels = np.array([0, 1, 2, 1, 0])

one_hot = np.eye(3)[labels]

print(one_hot)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


Calculate pairwise Euclidean distances.


Points:

P1 = (1,2)
P2 = (4,6)
P3 = (7,8)

P1 → P2:

$$ \sqrt{(4-1)^2 + (6-2)^2} = 5 $$

P2 → P3:

$$ \sqrt{(7-4)^2 + (8-6)^2} = 3.606 $$

P1 → P3:

$$ \sqrt{(7-1)^2 + (8-2)^2} = 8.485 $$

Isliye matrix mein diagonal 0 hota hai, aur matrix symmetric hoti hai.

Interview point: Pairwise distance ka use clustering, KNN, similarity/search, ML aur RAG-related vector comparisons mein hota hai.

In [129]:
points = np.array([
    [1, 2],
    [4, 6],
    [7, 8]
])


distance = np.linalg.norm(points[:, np.newaxis] - points, axis=2)
print(distance)

[[0.         5.         8.48528137]
 [5.         0.         3.60555128]
 [8.48528137 3.60555128 0.        ]]


Implement Min-Max normalization.

Min-Max Normalization means data should be in fixed range usualy 0 to 1, 


Formula:  X<sub>norm</sub> = X - X<sub>min</sub> / X<sub>max</sub> - X<sub>min</sub>
	​

	​



In [130]:
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


Implement standardization without sklearn.

In [131]:
arr = np.array([10, 20, 30, 40, 50])

mean = np.mean(arr)
std = np.std(arr)

standardized = (arr - mean) / std

print(standardized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


Implement simple linear regression using NumPy.

In [135]:
x= np.array([1,2,3,4,5])
y= np.array([2,4,5,8,10])

# Mean

x_mean = np.mean(x)
y_mean = np.mean(y)


# Slope (b1)

b1 = np.sum((x - x_mean) * (y - y_mean)) / np.sum((x - x_mean) ** 2)

# Intercept (b0)
b0 = y_mean - b1 * x_mean

# Predictions
y_pred = b0 + b1 * x

print("slope: ", b1)
print("Intercept: ", b0)
print("Predictions: ", y_pred)

slope:  2.0
Intercept:  -0.20000000000000018
Predictions:  [1.8 3.8 5.8 7.8 9.8]
