In [65]:
import numpy as np


Create a NumPy array from a Python list.

In [66]:
ll = [1,0,2,0,25,36,5]
print(type(ll))
ll = np.array(ll)
print(ll)
print(type(ll))

<class 'list'>
[ 1  0  2  0 25 36  5]
<class 'numpy.ndarray'>


In [67]:
ll = np.array([])

In [68]:

np.append(ll, 10)

array([10.])

Create an array containing numbers 1–100.

In [69]:
ll = np.array([x for x in range(1,101)])
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [70]:
ll = np.arange(1,101)
print(ll)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


Create a 5×5 array of zeros.

In [71]:
ll = np.zeros((5,5))
print(ll)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [72]:
ll = np.zeros((5,5), dtype=int)

In [73]:
ll

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Create a 3×4 array of ones.

In [74]:
ll = np.ones((3,4))
ll

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [75]:
ll = np.ones((3,4), int)
ll

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

Create a 5×5 identity matrix.

In [76]:
ll = np.identity(5, dtype=int)
ll

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create an array of even numbers from 2–100.

In [77]:
ll = np.array([x for x in range(2,100) if x %2 == 0])

ll

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [78]:
ll = np.arange(2,101,2)
ll

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create an array of odd numbers from 1–99.

In [79]:
ll = np.arange(1,99, 2)
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97])

In [80]:
ll = np.array([x for x in range(1,101) if x%2 == 1])
ll

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

Create a 3×3 matrix containing 1–9.

In [81]:
ll = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(ll)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
ll = np.arange(1,10).reshape(3,3)
ll

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Reshape a 1D array into a 2D matrix.

In [83]:
ll = np.arange(1,21)

In [84]:
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
ll = ll.reshape(4,5)

ll

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Flatten a 2D array.

In [86]:
ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Convert a 2D array into 1D.

In [87]:
ll = ll.reshape(4,5)

ll = ll.flatten()
ll

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Find the shape of an array.

In [88]:
ll = ll.reshape(4,5)

In [89]:
ll.shape

(4, 5)

Find the number of dimensions.

In [91]:
ll.ndim

2

Find the total number of elements.

In [92]:
ll.size

20

Find the data type.

In [93]:
ll.dtype

dtype('int64')

Change the data type.

In [99]:
ll = ll.astype(float)

ll.dtype

dtype('float64')

In [ ]:
import random


TypeError: 'module' object is not callable